// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FetchGamesController from "./fetch_games_controller"
application.register("fetch-games", FetchGamesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
