// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AjaxBanController from "./ajax_ban_controller"
application.register("ajax-ban", AjaxBanController)

import AjaxUndoController from "./ajax_undo_controller"
application.register("ajax-undo", AjaxUndoController)

import CookieClickerController from "./cookie_clicker_controller"
application.register("cookie-clicker", CookieClickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
